# Generated by Django 6.1.1 on 2026-09-15 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_command', models.CharField(help_text='Ex : nmap', max_length=100)),
                ('phase', models.CharField(choices=[('passive', 'Passive'), ('active', 'Active')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ex : snmp-info', max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='recon.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='ToolOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nom affiché, ex : Détection de version', max_length=100)),
                ('flag', models.CharField(help_text='Ex : -sV ou --script=', max_length=50)),
                ('option_type', models.CharField(choices=[('switch', 'Interrupteur (on/off)'), ('single_choice', 'Choix unique'), ('free_value', 'Valeur libre'), ('multi_choice', 'Choix multiple')], max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('catalog', models.ForeignKey(blank=True, help_text="Catalogue cherchable à proposer (seulement utile pour le type 'valeur libre')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.catalog')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recon.tool')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToolOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ex : -sS', max_length=100)),
                ('label', models.CharField(help_text='Ex : TCP SYN scan', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='recon.tooloption')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
