# Generated by Django 6.1.1 on 2026-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_catalog_tool_catalogentry_tooloption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooloption',
            name='flag',
            field=models.CharField(blank=True, help_text='Ex : -sV ou --script= (laisser vide si chaque choix a son propre flag)', max_length=50),
        ),
    ]
