# Generated by Django 6.1.1 on 2026-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_alter_tooloption_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex : Scan rapide', max_length=150)),
                ('phase', models.CharField(choices=[('passive', 'Passive'), ('active', 'Active')], max_length=10)),
                ('template', models.CharField(help_text='Utilise {address} pour représenter la cible, ex : nmap -F {address}', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
