# Generated by Django 6.1.1 on 2026-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0004_commandpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandpreset',
            name='category',
            field=models.CharField(blank=True, help_text='Ex : SMB, FTP, SSH, Général...', max_length=50),
        ),
    ]
