# Generated by Django 6.1.1 on 2026-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0007_seed_more_command_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooloption',
            name='group',
            field=models.CharField(blank=True, help_text='Ex : Détection, Scan, Performance...', max_length=50),
        ),
    ]
