# Generated by Django 6.1.1 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0008_tooloption_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='target_field',
            field=models.CharField(choices=[('address', 'Adresse (IP)'), ('domain', 'Nom de domaine')], default='address', max_length=10),
        ),
    ]
