# Generated by Django 6.1.1 on 2026-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0009_tool_target_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='target_flag',
            field=models.CharField(blank=True, help_text="Si la cible doit être précédée d'un flag (ex : -d), sinon elle est ajoutée telle quelle à la fin", max_length=20),
        ),
    ]
