# Generated by Django 6.1.1 on 2026-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('query_type', models.CharField(choices=[('domain', 'Domaine')], default='domain', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('finished', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('job_key', models.CharField(blank=True, max_length=50)),
                ('results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
