# Generated by Django 6.1.1 on 2026-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
