# Generated by Django 6.1.1 on 2026-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critique'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], max_length=10),
        ),
    ]
